/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.biocliq.fluwiz.dataloader.xls;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
